import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nizzi Abi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`overflow-x-hidden bg-neutral-950 text-white ${inter.className} bg-[radial-gradient(#2e2e2e_1px,transparent_1px)] [background-size:16px_16px]`}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  )
}
